### PR TITLE
#Fixes 51 : Add Responsive Navbar

### PR DESCRIPTION
**Pull request by Darshan1904**
### Description:
This pull request addresses issue #51 by adding a responsive navbar to the project. 

### Changes Made:
1. Implemented a responsive navbar that adapts to different screen sizes.
2. Fixed issue #51.
3. Ensured that the navbar remains user-friendly and accessible on all platforms.

### Testing:
I have thoroughly tested the changes on various devices and screen sizes to ensure that the responsive navbar functions as expected. This includes desktop, tablet, and mobile devices.

### Screenshots:
https://github.com/gdsc-abesit/GDSC-ABESIT/assets/113700964/e8298cc5-fd20-49ea-a39d-c037e52096ad

Please review and merge the pull request. Thank you!

### CODE REVIEW

**Comment by Darshan1904** [comment]
@prnvtripathi Please review this pull request.

**Comment by Ishaan2053** [comment]
Looks pretty aweome! 
Can you increase the vertical spacing between the links a little before we go ahead with merging? That'll be perfect :)

**Comment by Darshan1904** [comment]
Sure !!

Screenshot 2023-10-10 231840

Is it okay?. Review it so that i can commit changes.

**Comment by Ishaan2053** [comment]
Looks good to merge now!
Thank you for contributing :)

**Pull request merged**
