### PR TITLE
Created the README

### PR DESCRIPTION
**Pull request by Arcturus22**
Solved the issue #11 
@Keshav-0907

### CODE REVIEW

**Review by JoshLamptey — CHANGES_REQUESTED** [review]
I was thinking you'd add a how-to contribute section, or you'll create a separate file for that

**Review by JoshLamptey — APPROVED** [review]

**Comment by Arcturus22** [comment]
@JoshLamptey 
I thought that will be in the other issue #13 where it will include the how-to contribute section. 
I have solved the issue #11 to update the README file

**Comment by JoshLamptey** [comment]
Yes, you are right.
I'll take a look at issue #13

**Comment by Arcturus22** [comment]
@JoshLamptey 
So will you be merging this PR or are you suggesting some changes?

**Comment by JoshLamptey** [comment]
> @JoshLamptey 
> FOR ISSUE #11 
> So will you be merging this PR or are you suggesting some changes?  

It's already been merged

**Comment by Arcturus22** [comment]
> > @JoshLamptey
> > FOR ISSUE #11
> > So will you be merging this PR or are you suggesting some changes?
> 
> It's already been merged

Thanks

**Pull request merged**
