### PR TITLE
Load More Button And Added Generic Images

### PR DESCRIPTION
**Pull request by Ayusht777**
Added Feature like Load More Button And Added Generic Images

image

### CODE REVIEW

**Comment by Ishaan2053** [comment]
Hey Ayush, I've a few pointers to share after reviewing the PR:
- Directly editing someone else's card isn't what we were looking for. The contributors' array is edited by **each contributor for their own card.** We were looking for an event handler function that checks if the image does load for each card, and if it doesn't then assign a generic image to that specific card. It's great if you can make it work, but if you're not able to figure this out kindly revert it to its original state.

- The 'load more' button you created looks great, but the page would be even better if **by default 10 cards are shown** (that would be the initial two rows). the addition of 10 more cards on each click is perfect.
- Where is Vite used in this? I see it as an addition to `package.json`. If it's not used, please remove it.

Please look into remediating the above issues before we go ahead with merging this PR.

**Comment by Ayusht777** [comment]
i will try for the generic image part also i will change loading image by default to 10 and vite is use to run these project I didn't use CRA because it is slow and anything else you want  i will change it

**Comment by Ayusht777** [comment]
hey i update it and the generic version of images on card is not working and also i want to suggest you that can all the data of contributor can be put in different file like data.js for better readability of the code

**Comment by Ayusht777** [comment]
also adding clear input field button in contact from section

**Comment by Ayusht777** [comment]
can you merge it after checking it

**Review by Ishaan2053 — APPROVED** [review]

**Comment by Ishaan2053** [comment]
I removed Vite as a dependency from `package.json` because this website was scaffolded with Next.js on top of React and should intently be the primary way to run this website locally.

Should you wish to contribute more in the future, please omit Vite from your commits.
Other than that, the changes look good to merge!
Thanks for contributing :)

**Comment by Ayusht777** [comment]
@Ishaan2053  ok i will not push vite again and any new issue

**Comment by Ishaan2053** [comment]
Have a look, see what issues you can find and start working on them under the hacktoberfest label!

**Pull request merged**
